plugins {
    alias(libs.plugins.android.library)
    `maven-publish`
    signing
    alias(libs.plugins.nmcp)
    alias(libs.plugins.dokka)
}

base.archivesName = "smartfoo-android-lib-core"
description = "SmartFoo Core Library for Android"
group = "com.smartfoo"
version = providers.gradleProperty("releaseVersion").getOrElse("1.0.0")

//def siteUrl = "https://github.com/SmartFoo/smartfoo"
//def gitUrl = "https://github.com/SmartFoo/smartfoo.git"

dependencies {
    //implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.recyclerview)
    implementation(libs.google.android.material)

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.test.espresso.core)
}

android {
    namespace = "com.smartfoo.android.core"
    compileSdk = 37
    defaultConfig {
        minSdk = 34

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")
    }
    buildTypes {
        release {
            isMinifyEnabled = false
            isShrinkResources = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
        debug {
            isMinifyEnabled = false
            isShrinkResources = false

            // NOTE: Setting this to true can mess up debugging by hiding method parameters (especially anonymous methods)
            // If you are seeing weird missing variables when debugging, set this to false.
            // DO NOT CHECK THIS IN AS "false"!
            enableUnitTestCoverage = true
            enableAndroidTestCoverage = true
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
        }
    }
    buildFeatures {
        buildConfig = true
    }
    /*
    if (getIsLocalDevelopmentBuild()) {
        defaultPublishConfig = "debug"
    }
    */
    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

/*
tasks.withType(JavaCompile) {
    options.compilerArgs << "-Xlint:unchecked"
}
*/

// Credentials are read from ~/.gradle/gradle.properties (local) or env vars (CI).
// See publishing setup docs in the project README.
nmcp {
    centralPortal {
        username.set(providers.gradleProperty("mavenCentralUsername")
            .orElse(providers.environmentVariable("MAVEN_CENTRAL_USERNAME")))
        password.set(providers.gradleProperty("mavenCentralPassword")
            .orElse(providers.environmentVariable("MAVEN_CENTRAL_PASSWORD")))
        // USER_MANAGED lets you review the deployment in the Central Portal UI before publishing.
        // Switch to AUTOMATIC once you've confirmed the first upload looks correct.
        publishingType.set("USER_MANAGED")
    }
}

val dokkaJavadocJar by tasks.registering(Jar::class) {
    group = JavaBasePlugin.DOCUMENTATION_GROUP
    description = "Assembles a JAR containing Javadoc generated by Dokka"
    val dokkaJavadoc = tasks.named("dokkaJavadoc")
    dependsOn(dokkaJavadoc)
    from(dokkaJavadoc.map { it.outputs.files })
    archiveClassifier.set("javadoc")
}

// afterEvaluate required because the Android "release" component isn't available until after evaluation.
afterEvaluate {
    publishing {
        publications {
            create<MavenPublication>("release") {
                from(components["release"])
                artifact(dokkaJavadocJar)
                groupId    = "com.smartfoo"
                artifactId = "smartfoo-android-lib-core"
                version    = project.version.toString()
                pom {
                    name        = "SmartFoo Android Core Library"
                    description = "Cross-platform abstraction layer for Android"
                    url         = "https://github.com/SmartFoo/smartfoo"
                    licenses {
                        license {
                            name = "The MIT License"
                            url  = "https://raw.githubusercontent.com/SmartFoo/smartfoo/master/LICENSE"
                        }
                    }
                    developers {
                        developer {
                            id    = "paulpv"
                            name  = "Paul Peavyhouse"
                            email = "pv@swooby.com"
                        }
                    }
                    scm {
                        connection          = "scm:git:git://github.com/SmartFoo/smartfoo.git"
                        developerConnection = "scm:git:ssh://github.com/SmartFoo/smartfoo.git"
                        url                 = "https://github.com/SmartFoo/smartfoo"
                    }
                }
            }
        }
    }

    signing {
        val signingKey: String?      by project
        val signingPassword: String? by project
        useInMemoryPgpKeys(signingKey, signingPassword)
        sign(publishing.publications["release"])
    }
}
