name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 21
    defaults:
      run:
        shell: bash
        working-directory: ./android
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      env:
        # Increase GitHub rate limits, per:
        # https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#jetbrains
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'jetbrains'
        cache: gradle
    - run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
