name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 21
    defaults:
      run:
        shell: bash
        working-directory: ./android
    steps:
      - name: Checkout code and submodule(s)
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'jetbrains'
          cache: gradle

      - run: chmod +x gradlew

      - name: Publish to Maven Central
        run: ./gradlew :smartfoo-android-lib-core:publishAllPublicationsToCentralPortal -PreleaseVersion=${GITHUB_REF_NAME#v}
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}
